[project]
name = "s3cima"
version = "0.1.10"
description = "Supervised Spatial Single-Cell Image Analysis for identification of disease associated cell type composition in the tissue microenvironment"
authors = [
    {name = "gabriel-dvl",email = "gduvalkieffer@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pandas",
    "scikit-learn",
    "scipy",
    "matplotlib",
    "plotly",
    "nbformat (>=4.2.0)",
    "tqdm",
    "torch"
]

[tool.poetry]
version = "0.1.10"

[tool.poetry.dependencies]
python = ">=3.10"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
